### ISSUE TITLE
Don't require code checkout in /code/ctrueden

### ISSUE THREAD

**Issue by hinerm** [ctrueden/dotfiles#2]
The current `bashrc.stub` hard-codes a path to `$HOME/code/ctrueden/dotfiles`.. maybe this file could be generated by `config-links.sh` to use `CONFIG_DIR`

**Comment by ctrueden** [comment]
Fixed in 7dcc6c8119097364175fe4e066ce45e503523784, with further improvements in 6e311511672ddd9101e6e1222ddd43abd9b8151a.
