### ISSUE TITLE
java aliases don't work on linux

### ISSUE THREAD

**Issue by hinerm** [ctrueden/dotfiles#3]
`j6`, `j7` and `j8` are currently OSX-only.

Would be nice to do this on Linux. Installed JVMs create a `/usr/lib/jvm/.<jname>.jinfo` file. `<jname>` can then be passed to `update-java-alternatives` to get the `$JAVA_HOME` directory.

**Comment by ctrueden** [comment]
Progress on 6b82e09bb31082b91b7945faa1ce1acbe89f98b9. But still doesn't fully work.

**Comment by hinerm** [comment]
note that using `1.6, 1.7, 1.8` won't work as it's not compatible with oracle java 6/7/8.

Also updating `JAVA_HOME` won't update the executables
