### ISSUE TITLE
Add linux bash completion

### ISSUE THREAD

**Issue by hinerm** [ctrueden/dotfiles#7]
https://github.com/ctrueden/dotfiles/commit/01932286ea6b6c685198e359e0da1a9c06132bf9 broke git bash completion on linux for me. Not sure off-hand the best way to fix.

**Comment by ctrueden** [comment]
I can't fix it without more information. You can play with the output of `__git_ps1` and see what you find. The reason I changed it is because I was getting false positives for Git completion being available on some systems where it actually wasn't...
