### ISSUE TITLE
Java home commands should prefer JDK to JRE

### ISSUE THREAD

**Issue by hinerm** [ctrueden/dotfiles#8]
Can only confirm this is a problem on linux.

Instead of preferring openjdk to oracle java, we should make a best effort to ensure a JDK is used - and never pick a JRE if a JDK is available.

Possibly these should just never set java home to a JRE install, as it's pretty annoying when you're trying to switch compilers for Maven.

**Comment by ctrueden** [comment]
It's been a long time, and I haven't come across this issue on my Linux setups, so I'm gonna close this. If it's still annoying, we can reopen though and address it.
